version: '3.1'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: locatify
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data